FROM node:10

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Create app directory
WORKDIR /usr/src

# Install app dependencies
COPY package*.json yarn.lock ./
RUN yarn install --production

# Copy app source code
COPY . .

# Compile Typescript to Javascript
RUN yarn run tsc

#Expose port and start application
EXPOSE 3000
CMD [ "yarn", "start" ]