FROM node:10

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Create app directory
WORKDIR /usr/app

# Install app dependencies
COPY package*.json yarn.lock tsconfig.json nodemon.json ./
RUN yarn install

#Expose port and start application
EXPOSE 3001
CMD [ "yarn", "run", "debug" ]
